import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

const Home: NextPage = () => {
   return (
      <div>
         <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         <main>
            <h1>
               Welcome to <a href="https://nextjs.org">Next.js!</a>
            </h1>

            <Image
               src="/vercel.svg" // Route of the image file
               height={333} // Desired size with correct aspect ratio
               width={333} // Desired size with correct aspect ratio
               alt="Your Name"
            />

            <br />
            <br />
            <Link href="/post">
               <a>Posts</a>
            </Link>
         </main>
      </div>
   )
}

export default Home
